### ISSUE TITLE
Add stylus as style preprocessor

### ISSUE THREAD

**Issue by smogg** [EwaTrzemzalska/zjemto#27]
Writing plain CSS is a thing from the middle ages. We will add http://stylus-lang.com/ to our project.

### Todo:
- [x] Install and save Stylus as project dependency (you can search for npm packages here: https://www.npmjs.com/)
- [x] Add stylus file
- [x] Figure out how to compile that file to CSS from the command line using Stylus cli
- [x] Create `./scripts/styles` script and put that working command in there. Make sure the script is working
- [x] Add `./scripts/styles` to `./scripts/dev` script so you can run everything with a single command:
You can run two commands at the same time from a single script by using an ampersand `&` like this:

```
./scripts/script1.sh & ./scripts/script2.sh
```
